## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
podman.pkg-path = "podman"
raycast.pkg-path = "raycast"
raycast.systems = ["aarch64-darwin", "x86_64-darwin"]
helix.pkg-path = "helix"
gitui.pkg-path = "gitui"
lima.pkg-path = "lima"
xz.pkg-path = "xz"
_1password-cli.pkg-path = "_1password-cli"
exa = { pkg-path = "exa", pkg-group = "exa" }
ollama.pkg-path = "ollama"
huggingface-hub = { pkg-path = "python39Packages.huggingface-hub", pkg-group = "hg" }
llama-cpp.pkg-path = "llama-cpp"
pandoc.pkg-path = "pandoc"
nodejs = { pkg-path = "nodejs", pkg-group = "node-vscode"}
prettier.pkg-path = "nodePackages.prettier"
starship.pkg-path = "starship"
github-cli.pkg-path = "github-cli"
# gum.pkg-path = "gum"
# gum.version = "^0.14.5"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"
EDITOR="hx"
FLOX_PROMPT_DISABLE="1"

## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
common = '''
  alias ic='ibmcloud'
  alias iks='ibmcloud ks'
  alias roks='ibmcloud oc'
  alias vpc='ibmcloud is'
  alias c='podman ps'
  alias gi='gh issue'
  alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
  alias ls='exa'
  autoload -U colors; colors
  export KUBECONFIG=`mktemp`
  export PATH="$PATH:/Users/jtp/.local/bin:/usr/local/bin"
  export HISTFILE=~/.zsh_history
  export SAVEHIST=1000
  setopt inc_append_history share_history
'''

# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
